export const featureImages = [
  { src: "/images/img-002.jpg", label: "Grand wedding stage" },
  { src: "/images/img-003.jpg", label: "Royal floral aisle" },
  { src: "/images/img-004.jpg", label: "Open-air mandap" },
  { src: "/images/img-005.jpg", label: "Lounge and mandap" },
  { src: "/images/img-017.jpg", label: "Palatial decor" },
];

export const services = [
  {
    tag: "Weddings",
    title: "Weddings",
    copy: "Custom-designed weddings that reflect each couple's personality—from intimate garden affairs to grand ballroom galas.",
    cover: "/images/img-018.jpg",
  },
  {
    tag: "Pre-wedding",
    title: "Sangeet",
    copy: "High-energy sangeets with choreography, anchors, music, and entertainment that bring both families together.",
    cover: "/images/img-028.jpg",
  },
  {
    tag: "Pre-wedding",
    title: "Mehndi",
    copy: "Colourful mehndis with decor, pro artists, music, and hospitality for a relaxed, joyful gathering.",
    cover: "/images/img-037.jpg",
  },
  {
    tag: "Pre-wedding",
    title: "Haldi",
    copy: "Vibrant haldis with floral touches and lively ambience designed for laughter and fun.",
    cover: "/images/img-054.jpg",
  },
  {
    tag: "Wedding",
    title: "Receptions",
    copy: "Elegant receptions with curated food, music, and atmosphere for effortless mingling.",
    cover: "/images/img-032.jpg",
  },
  {
    tag: "Family",
    title: "Cradle Ceremonies",
    copy: "Graceful welcomes blending tradition with soft, thoughtful decor and family-focused details.",
    cover: "/images/img-059.jpg",
  },
  {
    tag: "Milestones",
    title: "Birthdays",
    copy: "Memorable birthdays—from intimate dinners to themed parties—designed around the guest of honour.",
    cover: "/images/img-068.jpg",
  },
  {
    tag: "Milestones",
    title: "Engagements",
    copy: "Engagement ceremonies that begin the journey with tasteful decor and curated experiences.",
    cover: "/images/img-028.jpg",
  },
];

export const galleryImages = [
  "img-002.jpg",
  "img-003.jpg",
  "img-004.jpg",
  "img-005.jpg",
  "img-006.jpg",
  "img-007.jpg",
  "img-009.jpg",
  "img-011.jpg",
  "img-012.jpg",
  "img-014.jpg",
  "img-016.jpg",
  "img-017.jpg",
  "img-018.jpg",
  "img-023.jpg",
  "img-024.jpg",
  "img-025.jpg",
  "img-027.jpg",
  "img-028.jpg",
  "img-030.jpg",
  "img-032.jpg",
  "img-033.jpg",
  "img-034.jpg",
  "img-035.jpg",
  "img-037.jpg",
  "img-038.jpg",
  "img-039.jpg",
  "img-041.jpg",
  "img-042.jpg",
  "img-043.jpg",
  "img-044.jpg",
  "img-045.jpg",
  "img-046.jpg",
  "img-047.jpg",
  "img-051.jpg",
  "img-052.jpg",
  "img-053.jpg",
  "img-054.jpg",
  "img-055.jpg",
  "img-059.jpg",
  "img-060.jpg",
  "img-061.jpg",
  "img-062.jpg",
  "img-063.jpg",
  "img-065.jpg",
  "img-067.jpg",
  "img-068.jpg",
  "img-069.jpg",
  "img-070.jpg",
  "img-072.jpg",
  "img-073.jpg",
  "img-074.jpg",
  "img-077.jpg",
  "img-078.jpg",
  "img-080.jpg",
  "img-081.jpg",
  "img-082.jpg",
  "img-084.jpg",
].map((file) => ({ src: `/images/${file}`, title: "Event moment" }));
